version: "3.6"

services:
    db:
        image: postgres:11-alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: dev
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: dev
        ports:
            - "5432:5432"
    java:
        image: tomcat:9-jdk14-openjdk-oracle
        environment:
            CATALINA_OUT: /dev/stdout
        ports:
            - 8081:8080
        volumes:
            - ./target/conference-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/conference.war
volumes:
    postgres-data: